<?php
require_once './Templates/header.phtml';
?>


<main class="container">
    <form>
        <div class="mb-3">
            <label for="usuario" class="form-label">Usuario</label>
            <input type="usuario" class="form-control" id="usuario" name="usuario" aria-describedby="emailHelp">

        </div>
        <div class="mb-3">
            <label for="contraseña" class="form-label">contraseña</label>
            <input type="password" class="form-control" id="exampleInputPassword1" name="contraseña">
        </div>

        <button type="submit" class="btn btn-primary">Entrar</button>
    </form>
</main>


<?php
require_once './Templates/footer.phtml';
?>