<main>
    <p class="text-start fs-5">El objetivo de la app es tratar de brindar soluciones en el almacenamiento de datos de al usuarios.</p>
    <p class="text-center">De una forma clara y sencilla, clara y basica para que, nuestros clientes se adapten rapidamente a su uso</p>
    <p class="text-xxl-end">Nuestro principal objetivo es brindar soluciones, nosotros adaptarnos a sus necesidades...</p>
</main>