<?php

require_once 'Templates/header.phtml';
?>
<div class="mt-5 w-25 mx-auto">
    <form method="POST" action="autenticacion">
        <div class="form-group">
            <label for="text">Usuario</label>
            <input type="text" required class="form-control" id="usuario" name="usuario">
        </div>
        <div class="form-group">
            <label for="password">contraseña</label>
            <input type="password" required class="form-control" id="contraseña" name="contraseña">
        </div>

        <?php if ($error) : ?>
            <div class='alert alert-danger' role='alert'>
                <?= $error ?>
            </div>
        <?php endif ?>

        <button type="submit" class="btn btn-primary mt-3">Entrar</button>
    </form>
</div>